### ISSUE TITLE
Editing Mode Support

### ISSUE THREAD

**Issue by Sprocketer** [svonjoi/obsidian-heading-level-indent#15]
@svonjoi When we getting editing mode support?

**Comment by svonjoi** [comment]
[v2.0.0](https://github.com/svonjoi/obsidian-heading-level-indent/releases/tag/2.0.0) with beta edit mode support. For now is usable with but with some bugs like no indenting preview embeds in live-preview mode

you can download the latest release via brat specifying 2.0.0 version if u want help with testing and/or if you want to use it as is

[knowing issues section](https://github.com/svonjoi/obsidian-heading-level-indent?tab=readme-ov-file#knowing-issues)

**Comment by svonjoi** [comment]
i didnt know that there is a [css snippet](https://github.com/svonjoi/obsidian-heading-level-indent/issues/3#issuecomment-2019226237) that indent in edit mode in the same way

**Comment by svonjoi** [comment]
close as duplicate of #3
