### ISSUE TITLE
Always showing that there is an update

### ISSUE THREAD

**Issue by nny57** [svonjoi/obsidian-heading-level-indent#19]
![image](https://github.com/user-attachments/assets/25828d67-ef3a-41ba-b757-34d2c9e78a6e)

The plugin shows that it always has an update as shown in the image. Clicking update does nothing even though it shows that an update has been applied. I believe it might be due to the mismatch between the version number and the currently installed number.

**Comment by svonjoi** [comment]
was a mistake

#24
