### ISSUE TITLE
JS errors

### ISSUE THREAD

**Issue by replete** [svonjoi/obsidian-heading-level-indent#2]
Plugin 1.0.2
Obsidian 1.1.5
MacOS 13.2.1

<img width="524" alt="Screenshot 2023-02-26 at 21 54 24" src="https://user-images.githubusercontent.com/812139/221439779-24ed2859-6d66-4773-821e-264b8988cc61.png">

Just installed plugin, quick bug report. Will try again in the future

**Comment by svonjoi** [comment]
Thanks for catching that
