### ISSUE TITLE
Indenting is incorrect inside a list or outline

### ISSUE THREAD

**Issue by ironfroggy** [svonjoi/obsidian-heading-level-indent#7]
Given a simple list like:

```markdown
- ## Fruit
  - Apple
  - Orange
  - Banana
```

If I try to increment the "Fruit" line heading level, the heading prefix is added _before_ the bullet point, which is incorrect.

```markdown
# - ## Fruit
  - Apple
  - Orange
  - Banana
```

When it should be done inside the list item, like this:

```markdown
- ### Fruit
  - Apple
  - Orange
  - Banana
```

**Comment by svonjoi** [comment]
I think you have open the issue in the wrong plugin. This plug doen not change the interraction in source mode
